### ISSUE TITLE
trying to install the generator gets into a endless recurring process

### ISSUE THREAD

**Issue by shiamalon** [vivekmore/generator-jhipster-nav-element#11]
Hi,

First of all thanks for your work. 

I've found an issue that when I run
` npm install -g generator-jhipster-nav-element`
 it start to repeat the output endlessly until I exit. 

But everything is working fine I guess.. except some minor issues but I think you know about them since its a in development process

![image](https://user-images.githubusercontent.com/26623959/31140386-29595818-a86c-11e7-9f5c-0a6fab3a0ac9.png)

**Comment by vivekmore** [comment]
This should be fixed in `v1.4.13` - please let me know if that works for you
