### ISSUE TITLE
No exported member 'JhipsterSharedModule' with yarn start

### ISSUE THREAD

**Issue by davidishee** [vivekmore/generator-jhipster-nav-element#12]
I have a fairly clean JHipster project using Angular 4. I just upgraded it to v4.10.0 and tried to create an "about us" page. Everything compiles OK, but when I try to use "yarn start" it complains:

`ERROR in [at-loader] ./src/main/webapp/app/about-us/about-us.module.ts:4:10
    TS2305: Module '"C:/Users/david/eclipse-workspace/myproj/src/main/webapp/app/shared/index"' has no exported member 'JhipsterSharedModule'.

Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 849 bytes {0} [built]
            factory:137ms building:895ms = 1032ms
webpack: Failed to compile.`

**Comment by davidishee** [comment]
I looked around and found out that it should have been called "ElectricityChooserSharedModule" in my case. Maybe the generator didn't pick up baseName from .yo-rc.json? (just guessing)

**Comment by vivekmore** [comment]
Looks like a valid bug from initial reading.
I'll try to update the generator with the fix.

Thanks for bringing this to my attention.
