### ISSUE TITLE
the different bewteen AngularJS  vs angula (client-side) artifacts - is unclear 

### ISSUE THREAD

**Issue by drormik** [vivekmore/generator-jhipster-nav-element#13]
is this about generating different versions of angular or something else ??

when do i use the 
1. AngularJS application (assuming your page is called 'about-us') ??

and when 
2. Angular application (assuming your page is called 'about-us') ??

thanks

**Comment by vivekmore** [comment]
This (sub-) generator works on applications built using jhipster.
So depending on whether you chose AngularJS or Angular while scaffolding your application, this generator will create appropriate components for your navigation element.

**Comment by drormik** [comment]
thanks Vivek, I think it would be very beneficial if you indicate the angular versions, like so:

replace:

1. AngularJS application (assuming your page is called 'about-us'):
with 
1. **AngularJS v1.x**  application (assuming your page is called 'about-us'):


and replace:

2. Angular application (assuming your page is called 'about-us'):

with 

2. **Angular 4**  application (assuming your page is called 'about-us'):

**Comment by vivekmore** [comment]
Thank you for the suggestion.
It is worded so, because Angular 1.x is referred to as AngularJS and Angular2+ is referred to as Angular by the angular community.
