### ISSUE TITLE
CharAt Error In Nav-Element Generation

### ISSUE THREAD

**Issue by PrakashHartron** [vivekmore/generator-jhipster-nav-element#14]
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'charAt' of undefined

**Comment by vivekmore** [comment]
Can you provide a little more information for me to re-produce the issue?
- version of generator-jhipster your app was built on
- version of generator-jhipster-nav-element you're using
- your .yo-rc.json
- anything else you can provide to help me understand your project environment and when/where you get the issue
